// Code generated by go-swagger; DO NOT EDIT.

package service_instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rsampaio/gosb/models"
)

// ServiceInstanceProvisionReader is a Reader for the ServiceInstanceProvision structure.
type ServiceInstanceProvisionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ServiceInstanceProvisionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewServiceInstanceProvisionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewServiceInstanceProvisionCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 202:
		result := NewServiceInstanceProvisionAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewServiceInstanceProvisionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewServiceInstanceProvisionUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewServiceInstanceProvisionConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 412:
		result := NewServiceInstanceProvisionPreconditionFailed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewServiceInstanceProvisionUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewServiceInstanceProvisionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewServiceInstanceProvisionOK creates a ServiceInstanceProvisionOK with default headers values
func NewServiceInstanceProvisionOK() *ServiceInstanceProvisionOK {
	return &ServiceInstanceProvisionOK{}
}

/* ServiceInstanceProvisionOK describes a response with status code 200, with default header values.

OK
*/
type ServiceInstanceProvisionOK struct {
	Payload *models.ServiceInstanceProvisionResponse
}

func (o *ServiceInstanceProvisionOK) Error() string {
	return fmt.Sprintf("[PUT /v2/service_instances/{instance_id}][%d] serviceInstanceProvisionOK  %+v", 200, o.Payload)
}
func (o *ServiceInstanceProvisionOK) GetPayload() *models.ServiceInstanceProvisionResponse {
	return o.Payload
}

func (o *ServiceInstanceProvisionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceInstanceProvisionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceInstanceProvisionCreated creates a ServiceInstanceProvisionCreated with default headers values
func NewServiceInstanceProvisionCreated() *ServiceInstanceProvisionCreated {
	return &ServiceInstanceProvisionCreated{}
}

/* ServiceInstanceProvisionCreated describes a response with status code 201, with default header values.

Created
*/
type ServiceInstanceProvisionCreated struct {
	Payload *models.ServiceInstanceProvisionResponse
}

func (o *ServiceInstanceProvisionCreated) Error() string {
	return fmt.Sprintf("[PUT /v2/service_instances/{instance_id}][%d] serviceInstanceProvisionCreated  %+v", 201, o.Payload)
}
func (o *ServiceInstanceProvisionCreated) GetPayload() *models.ServiceInstanceProvisionResponse {
	return o.Payload
}

func (o *ServiceInstanceProvisionCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceInstanceProvisionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceInstanceProvisionAccepted creates a ServiceInstanceProvisionAccepted with default headers values
func NewServiceInstanceProvisionAccepted() *ServiceInstanceProvisionAccepted {
	return &ServiceInstanceProvisionAccepted{}
}

/* ServiceInstanceProvisionAccepted describes a response with status code 202, with default header values.

Accepted
*/
type ServiceInstanceProvisionAccepted struct {
	Payload *models.ServiceInstanceAsyncOperation
}

func (o *ServiceInstanceProvisionAccepted) Error() string {
	return fmt.Sprintf("[PUT /v2/service_instances/{instance_id}][%d] serviceInstanceProvisionAccepted  %+v", 202, o.Payload)
}
func (o *ServiceInstanceProvisionAccepted) GetPayload() *models.ServiceInstanceAsyncOperation {
	return o.Payload
}

func (o *ServiceInstanceProvisionAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceInstanceAsyncOperation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceInstanceProvisionBadRequest creates a ServiceInstanceProvisionBadRequest with default headers values
func NewServiceInstanceProvisionBadRequest() *ServiceInstanceProvisionBadRequest {
	return &ServiceInstanceProvisionBadRequest{}
}

/* ServiceInstanceProvisionBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type ServiceInstanceProvisionBadRequest struct {
	Payload *models.Error
}

func (o *ServiceInstanceProvisionBadRequest) Error() string {
	return fmt.Sprintf("[PUT /v2/service_instances/{instance_id}][%d] serviceInstanceProvisionBadRequest  %+v", 400, o.Payload)
}
func (o *ServiceInstanceProvisionBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *ServiceInstanceProvisionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceInstanceProvisionUnauthorized creates a ServiceInstanceProvisionUnauthorized with default headers values
func NewServiceInstanceProvisionUnauthorized() *ServiceInstanceProvisionUnauthorized {
	return &ServiceInstanceProvisionUnauthorized{}
}

/* ServiceInstanceProvisionUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type ServiceInstanceProvisionUnauthorized struct {
	Payload *models.Error
}

func (o *ServiceInstanceProvisionUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /v2/service_instances/{instance_id}][%d] serviceInstanceProvisionUnauthorized  %+v", 401, o.Payload)
}
func (o *ServiceInstanceProvisionUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *ServiceInstanceProvisionUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceInstanceProvisionConflict creates a ServiceInstanceProvisionConflict with default headers values
func NewServiceInstanceProvisionConflict() *ServiceInstanceProvisionConflict {
	return &ServiceInstanceProvisionConflict{}
}

/* ServiceInstanceProvisionConflict describes a response with status code 409, with default header values.

Conflict
*/
type ServiceInstanceProvisionConflict struct {
	Payload *models.Error
}

func (o *ServiceInstanceProvisionConflict) Error() string {
	return fmt.Sprintf("[PUT /v2/service_instances/{instance_id}][%d] serviceInstanceProvisionConflict  %+v", 409, o.Payload)
}
func (o *ServiceInstanceProvisionConflict) GetPayload() *models.Error {
	return o.Payload
}

func (o *ServiceInstanceProvisionConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceInstanceProvisionPreconditionFailed creates a ServiceInstanceProvisionPreconditionFailed with default headers values
func NewServiceInstanceProvisionPreconditionFailed() *ServiceInstanceProvisionPreconditionFailed {
	return &ServiceInstanceProvisionPreconditionFailed{}
}

/* ServiceInstanceProvisionPreconditionFailed describes a response with status code 412, with default header values.

Precondition Failed
*/
type ServiceInstanceProvisionPreconditionFailed struct {
	Payload *models.Error
}

func (o *ServiceInstanceProvisionPreconditionFailed) Error() string {
	return fmt.Sprintf("[PUT /v2/service_instances/{instance_id}][%d] serviceInstanceProvisionPreconditionFailed  %+v", 412, o.Payload)
}
func (o *ServiceInstanceProvisionPreconditionFailed) GetPayload() *models.Error {
	return o.Payload
}

func (o *ServiceInstanceProvisionPreconditionFailed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceInstanceProvisionUnprocessableEntity creates a ServiceInstanceProvisionUnprocessableEntity with default headers values
func NewServiceInstanceProvisionUnprocessableEntity() *ServiceInstanceProvisionUnprocessableEntity {
	return &ServiceInstanceProvisionUnprocessableEntity{}
}

/* ServiceInstanceProvisionUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable Entity
*/
type ServiceInstanceProvisionUnprocessableEntity struct {
	Payload *models.Error
}

func (o *ServiceInstanceProvisionUnprocessableEntity) Error() string {
	return fmt.Sprintf("[PUT /v2/service_instances/{instance_id}][%d] serviceInstanceProvisionUnprocessableEntity  %+v", 422, o.Payload)
}
func (o *ServiceInstanceProvisionUnprocessableEntity) GetPayload() *models.Error {
	return o.Payload
}

func (o *ServiceInstanceProvisionUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceInstanceProvisionDefault creates a ServiceInstanceProvisionDefault with default headers values
func NewServiceInstanceProvisionDefault(code int) *ServiceInstanceProvisionDefault {
	return &ServiceInstanceProvisionDefault{
		_statusCode: code,
	}
}

/* ServiceInstanceProvisionDefault describes a response with status code -1, with default header values.

Unexpected
*/
type ServiceInstanceProvisionDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the service instance provision default response
func (o *ServiceInstanceProvisionDefault) Code() int {
	return o._statusCode
}

func (o *ServiceInstanceProvisionDefault) Error() string {
	return fmt.Sprintf("[PUT /v2/service_instances/{instance_id}][%d] serviceInstance.provision default  %+v", o._statusCode, o.Payload)
}
func (o *ServiceInstanceProvisionDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *ServiceInstanceProvisionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
