// Code generated by go-swagger; DO NOT EDIT.

package service_instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rsampaio/gosb/models"
)

// ServiceInstanceDeprovisionReader is a Reader for the ServiceInstanceDeprovision structure.
type ServiceInstanceDeprovisionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ServiceInstanceDeprovisionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewServiceInstanceDeprovisionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 202:
		result := NewServiceInstanceDeprovisionAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewServiceInstanceDeprovisionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewServiceInstanceDeprovisionUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 410:
		result := NewServiceInstanceDeprovisionGone()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 412:
		result := NewServiceInstanceDeprovisionPreconditionFailed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewServiceInstanceDeprovisionUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewServiceInstanceDeprovisionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewServiceInstanceDeprovisionOK creates a ServiceInstanceDeprovisionOK with default headers values
func NewServiceInstanceDeprovisionOK() *ServiceInstanceDeprovisionOK {
	return &ServiceInstanceDeprovisionOK{}
}

/* ServiceInstanceDeprovisionOK describes a response with status code 200, with default header values.

OK
*/
type ServiceInstanceDeprovisionOK struct {
	Payload interface{}
}

func (o *ServiceInstanceDeprovisionOK) Error() string {
	return fmt.Sprintf("[DELETE /v2/service_instances/{instance_id}][%d] serviceInstanceDeprovisionOK  %+v", 200, o.Payload)
}
func (o *ServiceInstanceDeprovisionOK) GetPayload() interface{} {
	return o.Payload
}

func (o *ServiceInstanceDeprovisionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceInstanceDeprovisionAccepted creates a ServiceInstanceDeprovisionAccepted with default headers values
func NewServiceInstanceDeprovisionAccepted() *ServiceInstanceDeprovisionAccepted {
	return &ServiceInstanceDeprovisionAccepted{}
}

/* ServiceInstanceDeprovisionAccepted describes a response with status code 202, with default header values.

Accepted
*/
type ServiceInstanceDeprovisionAccepted struct {
	Payload *models.AsyncOperation
}

func (o *ServiceInstanceDeprovisionAccepted) Error() string {
	return fmt.Sprintf("[DELETE /v2/service_instances/{instance_id}][%d] serviceInstanceDeprovisionAccepted  %+v", 202, o.Payload)
}
func (o *ServiceInstanceDeprovisionAccepted) GetPayload() *models.AsyncOperation {
	return o.Payload
}

func (o *ServiceInstanceDeprovisionAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AsyncOperation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceInstanceDeprovisionBadRequest creates a ServiceInstanceDeprovisionBadRequest with default headers values
func NewServiceInstanceDeprovisionBadRequest() *ServiceInstanceDeprovisionBadRequest {
	return &ServiceInstanceDeprovisionBadRequest{}
}

/* ServiceInstanceDeprovisionBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type ServiceInstanceDeprovisionBadRequest struct {
	Payload *models.Error
}

func (o *ServiceInstanceDeprovisionBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /v2/service_instances/{instance_id}][%d] serviceInstanceDeprovisionBadRequest  %+v", 400, o.Payload)
}
func (o *ServiceInstanceDeprovisionBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *ServiceInstanceDeprovisionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceInstanceDeprovisionUnauthorized creates a ServiceInstanceDeprovisionUnauthorized with default headers values
func NewServiceInstanceDeprovisionUnauthorized() *ServiceInstanceDeprovisionUnauthorized {
	return &ServiceInstanceDeprovisionUnauthorized{}
}

/* ServiceInstanceDeprovisionUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type ServiceInstanceDeprovisionUnauthorized struct {
	Payload *models.Error
}

func (o *ServiceInstanceDeprovisionUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /v2/service_instances/{instance_id}][%d] serviceInstanceDeprovisionUnauthorized  %+v", 401, o.Payload)
}
func (o *ServiceInstanceDeprovisionUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *ServiceInstanceDeprovisionUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceInstanceDeprovisionGone creates a ServiceInstanceDeprovisionGone with default headers values
func NewServiceInstanceDeprovisionGone() *ServiceInstanceDeprovisionGone {
	return &ServiceInstanceDeprovisionGone{}
}

/* ServiceInstanceDeprovisionGone describes a response with status code 410, with default header values.

Gone
*/
type ServiceInstanceDeprovisionGone struct {
	Payload *models.Error
}

func (o *ServiceInstanceDeprovisionGone) Error() string {
	return fmt.Sprintf("[DELETE /v2/service_instances/{instance_id}][%d] serviceInstanceDeprovisionGone  %+v", 410, o.Payload)
}
func (o *ServiceInstanceDeprovisionGone) GetPayload() *models.Error {
	return o.Payload
}

func (o *ServiceInstanceDeprovisionGone) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceInstanceDeprovisionPreconditionFailed creates a ServiceInstanceDeprovisionPreconditionFailed with default headers values
func NewServiceInstanceDeprovisionPreconditionFailed() *ServiceInstanceDeprovisionPreconditionFailed {
	return &ServiceInstanceDeprovisionPreconditionFailed{}
}

/* ServiceInstanceDeprovisionPreconditionFailed describes a response with status code 412, with default header values.

Precondition Failed
*/
type ServiceInstanceDeprovisionPreconditionFailed struct {
	Payload *models.Error
}

func (o *ServiceInstanceDeprovisionPreconditionFailed) Error() string {
	return fmt.Sprintf("[DELETE /v2/service_instances/{instance_id}][%d] serviceInstanceDeprovisionPreconditionFailed  %+v", 412, o.Payload)
}
func (o *ServiceInstanceDeprovisionPreconditionFailed) GetPayload() *models.Error {
	return o.Payload
}

func (o *ServiceInstanceDeprovisionPreconditionFailed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceInstanceDeprovisionUnprocessableEntity creates a ServiceInstanceDeprovisionUnprocessableEntity with default headers values
func NewServiceInstanceDeprovisionUnprocessableEntity() *ServiceInstanceDeprovisionUnprocessableEntity {
	return &ServiceInstanceDeprovisionUnprocessableEntity{}
}

/* ServiceInstanceDeprovisionUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable Entity
*/
type ServiceInstanceDeprovisionUnprocessableEntity struct {
	Payload *models.Error
}

func (o *ServiceInstanceDeprovisionUnprocessableEntity) Error() string {
	return fmt.Sprintf("[DELETE /v2/service_instances/{instance_id}][%d] serviceInstanceDeprovisionUnprocessableEntity  %+v", 422, o.Payload)
}
func (o *ServiceInstanceDeprovisionUnprocessableEntity) GetPayload() *models.Error {
	return o.Payload
}

func (o *ServiceInstanceDeprovisionUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceInstanceDeprovisionDefault creates a ServiceInstanceDeprovisionDefault with default headers values
func NewServiceInstanceDeprovisionDefault(code int) *ServiceInstanceDeprovisionDefault {
	return &ServiceInstanceDeprovisionDefault{
		_statusCode: code,
	}
}

/* ServiceInstanceDeprovisionDefault describes a response with status code -1, with default header values.

Unexpected
*/
type ServiceInstanceDeprovisionDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the service instance deprovision default response
func (o *ServiceInstanceDeprovisionDefault) Code() int {
	return o._statusCode
}

func (o *ServiceInstanceDeprovisionDefault) Error() string {
	return fmt.Sprintf("[DELETE /v2/service_instances/{instance_id}][%d] serviceInstance.deprovision default  %+v", o._statusCode, o.Payload)
}
func (o *ServiceInstanceDeprovisionDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *ServiceInstanceDeprovisionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
