// Code generated by go-swagger; DO NOT EDIT.

package service_instances

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rsampaio/gosb/models"
)

// ServiceInstanceLastOperationGetReader is a Reader for the ServiceInstanceLastOperationGet structure.
type ServiceInstanceLastOperationGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ServiceInstanceLastOperationGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewServiceInstanceLastOperationGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewServiceInstanceLastOperationGetBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewServiceInstanceLastOperationGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewServiceInstanceLastOperationGetNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 410:
		result := NewServiceInstanceLastOperationGetGone()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 412:
		result := NewServiceInstanceLastOperationGetPreconditionFailed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewServiceInstanceLastOperationGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewServiceInstanceLastOperationGetOK creates a ServiceInstanceLastOperationGetOK with default headers values
func NewServiceInstanceLastOperationGetOK() *ServiceInstanceLastOperationGetOK {
	return &ServiceInstanceLastOperationGetOK{}
}

/* ServiceInstanceLastOperationGetOK describes a response with status code 200, with default header values.

OK
*/
type ServiceInstanceLastOperationGetOK struct {

	/* Indicates when to retry the request
	 */
	RetryAfter string

	Payload *models.LastOperationResource
}

func (o *ServiceInstanceLastOperationGetOK) Error() string {
	return fmt.Sprintf("[GET /v2/service_instances/{instance_id}/last_operation][%d] serviceInstanceLastOperationGetOK  %+v", 200, o.Payload)
}
func (o *ServiceInstanceLastOperationGetOK) GetPayload() *models.LastOperationResource {
	return o.Payload
}

func (o *ServiceInstanceLastOperationGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header RetryAfter
	hdrRetryAfter := response.GetHeader("RetryAfter")

	if hdrRetryAfter != "" {
		o.RetryAfter = hdrRetryAfter
	}

	o.Payload = new(models.LastOperationResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceInstanceLastOperationGetBadRequest creates a ServiceInstanceLastOperationGetBadRequest with default headers values
func NewServiceInstanceLastOperationGetBadRequest() *ServiceInstanceLastOperationGetBadRequest {
	return &ServiceInstanceLastOperationGetBadRequest{}
}

/* ServiceInstanceLastOperationGetBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type ServiceInstanceLastOperationGetBadRequest struct {
	Payload *models.Error
}

func (o *ServiceInstanceLastOperationGetBadRequest) Error() string {
	return fmt.Sprintf("[GET /v2/service_instances/{instance_id}/last_operation][%d] serviceInstanceLastOperationGetBadRequest  %+v", 400, o.Payload)
}
func (o *ServiceInstanceLastOperationGetBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *ServiceInstanceLastOperationGetBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceInstanceLastOperationGetUnauthorized creates a ServiceInstanceLastOperationGetUnauthorized with default headers values
func NewServiceInstanceLastOperationGetUnauthorized() *ServiceInstanceLastOperationGetUnauthorized {
	return &ServiceInstanceLastOperationGetUnauthorized{}
}

/* ServiceInstanceLastOperationGetUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type ServiceInstanceLastOperationGetUnauthorized struct {
	Payload *models.Error
}

func (o *ServiceInstanceLastOperationGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v2/service_instances/{instance_id}/last_operation][%d] serviceInstanceLastOperationGetUnauthorized  %+v", 401, o.Payload)
}
func (o *ServiceInstanceLastOperationGetUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *ServiceInstanceLastOperationGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceInstanceLastOperationGetNotFound creates a ServiceInstanceLastOperationGetNotFound with default headers values
func NewServiceInstanceLastOperationGetNotFound() *ServiceInstanceLastOperationGetNotFound {
	return &ServiceInstanceLastOperationGetNotFound{}
}

/* ServiceInstanceLastOperationGetNotFound describes a response with status code 404, with default header values.

Not Found
*/
type ServiceInstanceLastOperationGetNotFound struct {
	Payload *models.Error
}

func (o *ServiceInstanceLastOperationGetNotFound) Error() string {
	return fmt.Sprintf("[GET /v2/service_instances/{instance_id}/last_operation][%d] serviceInstanceLastOperationGetNotFound  %+v", 404, o.Payload)
}
func (o *ServiceInstanceLastOperationGetNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *ServiceInstanceLastOperationGetNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceInstanceLastOperationGetGone creates a ServiceInstanceLastOperationGetGone with default headers values
func NewServiceInstanceLastOperationGetGone() *ServiceInstanceLastOperationGetGone {
	return &ServiceInstanceLastOperationGetGone{}
}

/* ServiceInstanceLastOperationGetGone describes a response with status code 410, with default header values.

Gone
*/
type ServiceInstanceLastOperationGetGone struct {
	Payload *models.Error
}

func (o *ServiceInstanceLastOperationGetGone) Error() string {
	return fmt.Sprintf("[GET /v2/service_instances/{instance_id}/last_operation][%d] serviceInstanceLastOperationGetGone  %+v", 410, o.Payload)
}
func (o *ServiceInstanceLastOperationGetGone) GetPayload() *models.Error {
	return o.Payload
}

func (o *ServiceInstanceLastOperationGetGone) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceInstanceLastOperationGetPreconditionFailed creates a ServiceInstanceLastOperationGetPreconditionFailed with default headers values
func NewServiceInstanceLastOperationGetPreconditionFailed() *ServiceInstanceLastOperationGetPreconditionFailed {
	return &ServiceInstanceLastOperationGetPreconditionFailed{}
}

/* ServiceInstanceLastOperationGetPreconditionFailed describes a response with status code 412, with default header values.

Precondition Failed
*/
type ServiceInstanceLastOperationGetPreconditionFailed struct {
	Payload *models.Error
}

func (o *ServiceInstanceLastOperationGetPreconditionFailed) Error() string {
	return fmt.Sprintf("[GET /v2/service_instances/{instance_id}/last_operation][%d] serviceInstanceLastOperationGetPreconditionFailed  %+v", 412, o.Payload)
}
func (o *ServiceInstanceLastOperationGetPreconditionFailed) GetPayload() *models.Error {
	return o.Payload
}

func (o *ServiceInstanceLastOperationGetPreconditionFailed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceInstanceLastOperationGetDefault creates a ServiceInstanceLastOperationGetDefault with default headers values
func NewServiceInstanceLastOperationGetDefault(code int) *ServiceInstanceLastOperationGetDefault {
	return &ServiceInstanceLastOperationGetDefault{
		_statusCode: code,
	}
}

/* ServiceInstanceLastOperationGetDefault describes a response with status code -1, with default header values.

Unexpected
*/
type ServiceInstanceLastOperationGetDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the service instance last operation get default response
func (o *ServiceInstanceLastOperationGetDefault) Code() int {
	return o._statusCode
}

func (o *ServiceInstanceLastOperationGetDefault) Error() string {
	return fmt.Sprintf("[GET /v2/service_instances/{instance_id}/last_operation][%d] serviceInstance.lastOperation.get default  %+v", o._statusCode, o.Payload)
}
func (o *ServiceInstanceLastOperationGetDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *ServiceInstanceLastOperationGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
