/*
 * Open Service Broker API
 *
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * API version: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package gosb

type ServiceBindingVolumeMount struct {
	Driver string `json:"driver"`
	ContainerDir string `json:"container_dir"`
	Mode string `json:"mode"`
	DeviceType string `json:"device_type"`
	Device *ServiceBindingVolumeMountDevice `json:"device"`
}
