/*
 * Open Service Broker API
 *
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * API version: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gosb

import (
	"encoding/json"
)

// ServiceInstanceSchema struct for ServiceInstanceSchema
type ServiceInstanceSchema struct {
	Create *ServiceInstanceSchemaCreate `json:"create,omitempty"`
	Update *ServiceInstanceSchemaCreate `json:"update,omitempty"`
}

// NewServiceInstanceSchema instantiates a new ServiceInstanceSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceInstanceSchema() *ServiceInstanceSchema {
	this := ServiceInstanceSchema{}
	return &this
}

// NewServiceInstanceSchemaWithDefaults instantiates a new ServiceInstanceSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceInstanceSchemaWithDefaults() *ServiceInstanceSchema {
	this := ServiceInstanceSchema{}
	return &this
}

// GetCreate returns the Create field value if set, zero value otherwise.
func (o *ServiceInstanceSchema) GetCreate() ServiceInstanceSchemaCreate {
	if o == nil || o.Create == nil {
		var ret ServiceInstanceSchemaCreate
		return ret
	}
	return *o.Create
}

// GetCreateOk returns a tuple with the Create field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceInstanceSchema) GetCreateOk() (*ServiceInstanceSchemaCreate, bool) {
	if o == nil || o.Create == nil {
		return nil, false
	}
	return o.Create, true
}

// HasCreate returns a boolean if a field has been set.
func (o *ServiceInstanceSchema) HasCreate() bool {
	if o != nil && o.Create != nil {
		return true
	}

	return false
}

// SetCreate gets a reference to the given ServiceInstanceSchemaCreate and assigns it to the Create field.
func (o *ServiceInstanceSchema) SetCreate(v ServiceInstanceSchemaCreate) {
	o.Create = &v
}

// GetUpdate returns the Update field value if set, zero value otherwise.
func (o *ServiceInstanceSchema) GetUpdate() ServiceInstanceSchemaCreate {
	if o == nil || o.Update == nil {
		var ret ServiceInstanceSchemaCreate
		return ret
	}
	return *o.Update
}

// GetUpdateOk returns a tuple with the Update field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceInstanceSchema) GetUpdateOk() (*ServiceInstanceSchemaCreate, bool) {
	if o == nil || o.Update == nil {
		return nil, false
	}
	return o.Update, true
}

// HasUpdate returns a boolean if a field has been set.
func (o *ServiceInstanceSchema) HasUpdate() bool {
	if o != nil && o.Update != nil {
		return true
	}

	return false
}

// SetUpdate gets a reference to the given ServiceInstanceSchemaCreate and assigns it to the Update field.
func (o *ServiceInstanceSchema) SetUpdate(v ServiceInstanceSchemaCreate) {
	o.Update = &v
}

func (o ServiceInstanceSchema) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Create != nil {
		toSerialize["create"] = o.Create
	}
	if o.Update != nil {
		toSerialize["update"] = o.Update
	}
	return json.Marshal(toSerialize)
}

type NullableServiceInstanceSchema struct {
	value *ServiceInstanceSchema
	isSet bool
}

func (v NullableServiceInstanceSchema) Get() *ServiceInstanceSchema {
	return v.value
}

func (v *NullableServiceInstanceSchema) Set(val *ServiceInstanceSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceInstanceSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceInstanceSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceInstanceSchema(val *ServiceInstanceSchema) *NullableServiceInstanceSchema {
	return &NullableServiceInstanceSchema{value: val, isSet: true}
}

func (v NullableServiceInstanceSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceInstanceSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


