/*
 * Open Service Broker API
 *
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * API version: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package gosb

type LastOperationResource struct {
	State string `json:"state"`
	Description string `json:"description,omitempty"`
	InstanceUsable bool `json:"instance_usable,omitempty"`
	UpdateRepeatable bool `json:"update_repeatable,omitempty"`
}
