/*
 * Open Service Broker API
 *
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * API version: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gosb

import (
	"encoding/json"
)

// ServiceInstanceSchemaCreate struct for ServiceInstanceSchemaCreate
type ServiceInstanceSchemaCreate struct {
	Parameters *map[string]interface{} `json:"parameters,omitempty"`
}

// NewServiceInstanceSchemaCreate instantiates a new ServiceInstanceSchemaCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceInstanceSchemaCreate() *ServiceInstanceSchemaCreate {
	this := ServiceInstanceSchemaCreate{}
	return &this
}

// NewServiceInstanceSchemaCreateWithDefaults instantiates a new ServiceInstanceSchemaCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceInstanceSchemaCreateWithDefaults() *ServiceInstanceSchemaCreate {
	this := ServiceInstanceSchemaCreate{}
	return &this
}

// GetParameters returns the Parameters field value if set, zero value otherwise.
func (o *ServiceInstanceSchemaCreate) GetParameters() map[string]interface{} {
	if o == nil || o.Parameters == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceInstanceSchemaCreate) GetParametersOk() (*map[string]interface{}, bool) {
	if o == nil || o.Parameters == nil {
		return nil, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *ServiceInstanceSchemaCreate) HasParameters() bool {
	if o != nil && o.Parameters != nil {
		return true
	}

	return false
}

// SetParameters gets a reference to the given map[string]interface{} and assigns it to the Parameters field.
func (o *ServiceInstanceSchemaCreate) SetParameters(v map[string]interface{}) {
	o.Parameters = &v
}

func (o ServiceInstanceSchemaCreate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Parameters != nil {
		toSerialize["parameters"] = o.Parameters
	}
	return json.Marshal(toSerialize)
}

type NullableServiceInstanceSchemaCreate struct {
	value *ServiceInstanceSchemaCreate
	isSet bool
}

func (v NullableServiceInstanceSchemaCreate) Get() *ServiceInstanceSchemaCreate {
	return v.value
}

func (v *NullableServiceInstanceSchemaCreate) Set(val *ServiceInstanceSchemaCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceInstanceSchemaCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceInstanceSchemaCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceInstanceSchemaCreate(val *ServiceInstanceSchemaCreate) *NullableServiceInstanceSchemaCreate {
	return &NullableServiceInstanceSchemaCreate{value: val, isSet: true}
}

func (v NullableServiceInstanceSchemaCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceInstanceSchemaCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


