/*
 * Open Service Broker API
 *
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * API version: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gosb

import (
	"encoding/json"
)

// ServiceInstanceProvisionRequestBody struct for ServiceInstanceProvisionRequestBody
type ServiceInstanceProvisionRequestBody struct {
	ServiceId string `json:"service_id"`
	PlanId string `json:"plan_id"`
	// See [Context Conventions](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#context-object) for more details.
	Context *map[string]interface{} `json:"context,omitempty"`
	OrganizationGuid string `json:"organization_guid"`
	SpaceGuid string `json:"space_guid"`
	Parameters *map[string]interface{} `json:"parameters,omitempty"`
}

// NewServiceInstanceProvisionRequestBody instantiates a new ServiceInstanceProvisionRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceInstanceProvisionRequestBody(serviceId string, planId string, organizationGuid string, spaceGuid string, ) *ServiceInstanceProvisionRequestBody {
	this := ServiceInstanceProvisionRequestBody{}
	this.ServiceId = serviceId
	this.PlanId = planId
	this.OrganizationGuid = organizationGuid
	this.SpaceGuid = spaceGuid
	return &this
}

// NewServiceInstanceProvisionRequestBodyWithDefaults instantiates a new ServiceInstanceProvisionRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceInstanceProvisionRequestBodyWithDefaults() *ServiceInstanceProvisionRequestBody {
	this := ServiceInstanceProvisionRequestBody{}
	return &this
}

// GetServiceId returns the ServiceId field value
func (o *ServiceInstanceProvisionRequestBody) GetServiceId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *ServiceInstanceProvisionRequestBody) GetServiceIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *ServiceInstanceProvisionRequestBody) SetServiceId(v string) {
	o.ServiceId = v
}

// GetPlanId returns the PlanId field value
func (o *ServiceInstanceProvisionRequestBody) GetPlanId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.PlanId
}

// GetPlanIdOk returns a tuple with the PlanId field value
// and a boolean to check if the value has been set.
func (o *ServiceInstanceProvisionRequestBody) GetPlanIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PlanId, true
}

// SetPlanId sets field value
func (o *ServiceInstanceProvisionRequestBody) SetPlanId(v string) {
	o.PlanId = v
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *ServiceInstanceProvisionRequestBody) GetContext() map[string]interface{} {
	if o == nil || o.Context == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceInstanceProvisionRequestBody) GetContextOk() (*map[string]interface{}, bool) {
	if o == nil || o.Context == nil {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *ServiceInstanceProvisionRequestBody) HasContext() bool {
	if o != nil && o.Context != nil {
		return true
	}

	return false
}

// SetContext gets a reference to the given map[string]interface{} and assigns it to the Context field.
func (o *ServiceInstanceProvisionRequestBody) SetContext(v map[string]interface{}) {
	o.Context = &v
}

// GetOrganizationGuid returns the OrganizationGuid field value
func (o *ServiceInstanceProvisionRequestBody) GetOrganizationGuid() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.OrganizationGuid
}

// GetOrganizationGuidOk returns a tuple with the OrganizationGuid field value
// and a boolean to check if the value has been set.
func (o *ServiceInstanceProvisionRequestBody) GetOrganizationGuidOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.OrganizationGuid, true
}

// SetOrganizationGuid sets field value
func (o *ServiceInstanceProvisionRequestBody) SetOrganizationGuid(v string) {
	o.OrganizationGuid = v
}

// GetSpaceGuid returns the SpaceGuid field value
func (o *ServiceInstanceProvisionRequestBody) GetSpaceGuid() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.SpaceGuid
}

// GetSpaceGuidOk returns a tuple with the SpaceGuid field value
// and a boolean to check if the value has been set.
func (o *ServiceInstanceProvisionRequestBody) GetSpaceGuidOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SpaceGuid, true
}

// SetSpaceGuid sets field value
func (o *ServiceInstanceProvisionRequestBody) SetSpaceGuid(v string) {
	o.SpaceGuid = v
}

// GetParameters returns the Parameters field value if set, zero value otherwise.
func (o *ServiceInstanceProvisionRequestBody) GetParameters() map[string]interface{} {
	if o == nil || o.Parameters == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceInstanceProvisionRequestBody) GetParametersOk() (*map[string]interface{}, bool) {
	if o == nil || o.Parameters == nil {
		return nil, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *ServiceInstanceProvisionRequestBody) HasParameters() bool {
	if o != nil && o.Parameters != nil {
		return true
	}

	return false
}

// SetParameters gets a reference to the given map[string]interface{} and assigns it to the Parameters field.
func (o *ServiceInstanceProvisionRequestBody) SetParameters(v map[string]interface{}) {
	o.Parameters = &v
}

func (o ServiceInstanceProvisionRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["service_id"] = o.ServiceId
	}
	if true {
		toSerialize["plan_id"] = o.PlanId
	}
	if o.Context != nil {
		toSerialize["context"] = o.Context
	}
	if true {
		toSerialize["organization_guid"] = o.OrganizationGuid
	}
	if true {
		toSerialize["space_guid"] = o.SpaceGuid
	}
	if o.Parameters != nil {
		toSerialize["parameters"] = o.Parameters
	}
	return json.Marshal(toSerialize)
}

type NullableServiceInstanceProvisionRequestBody struct {
	value *ServiceInstanceProvisionRequestBody
	isSet bool
}

func (v NullableServiceInstanceProvisionRequestBody) Get() *ServiceInstanceProvisionRequestBody {
	return v.value
}

func (v *NullableServiceInstanceProvisionRequestBody) Set(val *ServiceInstanceProvisionRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceInstanceProvisionRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceInstanceProvisionRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceInstanceProvisionRequestBody(val *ServiceInstanceProvisionRequestBody) *NullableServiceInstanceProvisionRequestBody {
	return &NullableServiceInstanceProvisionRequestBody{value: val, isSet: true}
}

func (v NullableServiceInstanceProvisionRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceInstanceProvisionRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


