// Code generated by go-swagger; DO NOT EDIT.

package service_bindings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rsampaio/gosb/models"
)

// ServiceBindingGetReader is a Reader for the ServiceBindingGet structure.
type ServiceBindingGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ServiceBindingGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewServiceBindingGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewServiceBindingGetUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewServiceBindingGetNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 412:
		result := NewServiceBindingGetPreconditionFailed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewServiceBindingGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewServiceBindingGetOK creates a ServiceBindingGetOK with default headers values
func NewServiceBindingGetOK() *ServiceBindingGetOK {
	return &ServiceBindingGetOK{}
}

/* ServiceBindingGetOK describes a response with status code 200, with default header values.

OK
*/
type ServiceBindingGetOK struct {
	Payload *models.ServiceBindingResource
}

func (o *ServiceBindingGetOK) Error() string {
	return fmt.Sprintf("[GET /v2/service_instances/{instance_id}/service_bindings/{binding_id}][%d] serviceBindingGetOK  %+v", 200, o.Payload)
}
func (o *ServiceBindingGetOK) GetPayload() *models.ServiceBindingResource {
	return o.Payload
}

func (o *ServiceBindingGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceBindingResource)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceBindingGetUnauthorized creates a ServiceBindingGetUnauthorized with default headers values
func NewServiceBindingGetUnauthorized() *ServiceBindingGetUnauthorized {
	return &ServiceBindingGetUnauthorized{}
}

/* ServiceBindingGetUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type ServiceBindingGetUnauthorized struct {
	Payload *models.Error
}

func (o *ServiceBindingGetUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v2/service_instances/{instance_id}/service_bindings/{binding_id}][%d] serviceBindingGetUnauthorized  %+v", 401, o.Payload)
}
func (o *ServiceBindingGetUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *ServiceBindingGetUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceBindingGetNotFound creates a ServiceBindingGetNotFound with default headers values
func NewServiceBindingGetNotFound() *ServiceBindingGetNotFound {
	return &ServiceBindingGetNotFound{}
}

/* ServiceBindingGetNotFound describes a response with status code 404, with default header values.

Not Found
*/
type ServiceBindingGetNotFound struct {
	Payload *models.Error
}

func (o *ServiceBindingGetNotFound) Error() string {
	return fmt.Sprintf("[GET /v2/service_instances/{instance_id}/service_bindings/{binding_id}][%d] serviceBindingGetNotFound  %+v", 404, o.Payload)
}
func (o *ServiceBindingGetNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *ServiceBindingGetNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceBindingGetPreconditionFailed creates a ServiceBindingGetPreconditionFailed with default headers values
func NewServiceBindingGetPreconditionFailed() *ServiceBindingGetPreconditionFailed {
	return &ServiceBindingGetPreconditionFailed{}
}

/* ServiceBindingGetPreconditionFailed describes a response with status code 412, with default header values.

Precondition Failed
*/
type ServiceBindingGetPreconditionFailed struct {
	Payload *models.Error
}

func (o *ServiceBindingGetPreconditionFailed) Error() string {
	return fmt.Sprintf("[GET /v2/service_instances/{instance_id}/service_bindings/{binding_id}][%d] serviceBindingGetPreconditionFailed  %+v", 412, o.Payload)
}
func (o *ServiceBindingGetPreconditionFailed) GetPayload() *models.Error {
	return o.Payload
}

func (o *ServiceBindingGetPreconditionFailed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceBindingGetDefault creates a ServiceBindingGetDefault with default headers values
func NewServiceBindingGetDefault(code int) *ServiceBindingGetDefault {
	return &ServiceBindingGetDefault{
		_statusCode: code,
	}
}

/* ServiceBindingGetDefault describes a response with status code -1, with default header values.

Unexpected
*/
type ServiceBindingGetDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the service binding get default response
func (o *ServiceBindingGetDefault) Code() int {
	return o._statusCode
}

func (o *ServiceBindingGetDefault) Error() string {
	return fmt.Sprintf("[GET /v2/service_instances/{instance_id}/service_bindings/{binding_id}][%d] serviceBinding.get default  %+v", o._statusCode, o.Payload)
}
func (o *ServiceBindingGetDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *ServiceBindingGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
