// Code generated by go-swagger; DO NOT EDIT.

package service_bindings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/rsampaio/gosb/models"
)

// ServiceBindingUnbindingReader is a Reader for the ServiceBindingUnbinding structure.
type ServiceBindingUnbindingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ServiceBindingUnbindingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewServiceBindingUnbindingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 202:
		result := NewServiceBindingUnbindingAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewServiceBindingUnbindingBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewServiceBindingUnbindingUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 410:
		result := NewServiceBindingUnbindingGone()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 412:
		result := NewServiceBindingUnbindingPreconditionFailed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewServiceBindingUnbindingUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewServiceBindingUnbindingDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewServiceBindingUnbindingOK creates a ServiceBindingUnbindingOK with default headers values
func NewServiceBindingUnbindingOK() *ServiceBindingUnbindingOK {
	return &ServiceBindingUnbindingOK{}
}

/* ServiceBindingUnbindingOK describes a response with status code 200, with default header values.

OK
*/
type ServiceBindingUnbindingOK struct {
	Payload interface{}
}

func (o *ServiceBindingUnbindingOK) Error() string {
	return fmt.Sprintf("[DELETE /v2/service_instances/{instance_id}/service_bindings/{binding_id}][%d] serviceBindingUnbindingOK  %+v", 200, o.Payload)
}
func (o *ServiceBindingUnbindingOK) GetPayload() interface{} {
	return o.Payload
}

func (o *ServiceBindingUnbindingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceBindingUnbindingAccepted creates a ServiceBindingUnbindingAccepted with default headers values
func NewServiceBindingUnbindingAccepted() *ServiceBindingUnbindingAccepted {
	return &ServiceBindingUnbindingAccepted{}
}

/* ServiceBindingUnbindingAccepted describes a response with status code 202, with default header values.

Accepted
*/
type ServiceBindingUnbindingAccepted struct {
	Payload *models.AsyncOperation
}

func (o *ServiceBindingUnbindingAccepted) Error() string {
	return fmt.Sprintf("[DELETE /v2/service_instances/{instance_id}/service_bindings/{binding_id}][%d] serviceBindingUnbindingAccepted  %+v", 202, o.Payload)
}
func (o *ServiceBindingUnbindingAccepted) GetPayload() *models.AsyncOperation {
	return o.Payload
}

func (o *ServiceBindingUnbindingAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AsyncOperation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceBindingUnbindingBadRequest creates a ServiceBindingUnbindingBadRequest with default headers values
func NewServiceBindingUnbindingBadRequest() *ServiceBindingUnbindingBadRequest {
	return &ServiceBindingUnbindingBadRequest{}
}

/* ServiceBindingUnbindingBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type ServiceBindingUnbindingBadRequest struct {
	Payload *models.Error
}

func (o *ServiceBindingUnbindingBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /v2/service_instances/{instance_id}/service_bindings/{binding_id}][%d] serviceBindingUnbindingBadRequest  %+v", 400, o.Payload)
}
func (o *ServiceBindingUnbindingBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *ServiceBindingUnbindingBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceBindingUnbindingUnauthorized creates a ServiceBindingUnbindingUnauthorized with default headers values
func NewServiceBindingUnbindingUnauthorized() *ServiceBindingUnbindingUnauthorized {
	return &ServiceBindingUnbindingUnauthorized{}
}

/* ServiceBindingUnbindingUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type ServiceBindingUnbindingUnauthorized struct {
	Payload *models.Error
}

func (o *ServiceBindingUnbindingUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /v2/service_instances/{instance_id}/service_bindings/{binding_id}][%d] serviceBindingUnbindingUnauthorized  %+v", 401, o.Payload)
}
func (o *ServiceBindingUnbindingUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *ServiceBindingUnbindingUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceBindingUnbindingGone creates a ServiceBindingUnbindingGone with default headers values
func NewServiceBindingUnbindingGone() *ServiceBindingUnbindingGone {
	return &ServiceBindingUnbindingGone{}
}

/* ServiceBindingUnbindingGone describes a response with status code 410, with default header values.

Gone
*/
type ServiceBindingUnbindingGone struct {
	Payload *models.Error
}

func (o *ServiceBindingUnbindingGone) Error() string {
	return fmt.Sprintf("[DELETE /v2/service_instances/{instance_id}/service_bindings/{binding_id}][%d] serviceBindingUnbindingGone  %+v", 410, o.Payload)
}
func (o *ServiceBindingUnbindingGone) GetPayload() *models.Error {
	return o.Payload
}

func (o *ServiceBindingUnbindingGone) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceBindingUnbindingPreconditionFailed creates a ServiceBindingUnbindingPreconditionFailed with default headers values
func NewServiceBindingUnbindingPreconditionFailed() *ServiceBindingUnbindingPreconditionFailed {
	return &ServiceBindingUnbindingPreconditionFailed{}
}

/* ServiceBindingUnbindingPreconditionFailed describes a response with status code 412, with default header values.

Precondition Failed
*/
type ServiceBindingUnbindingPreconditionFailed struct {
	Payload *models.Error
}

func (o *ServiceBindingUnbindingPreconditionFailed) Error() string {
	return fmt.Sprintf("[DELETE /v2/service_instances/{instance_id}/service_bindings/{binding_id}][%d] serviceBindingUnbindingPreconditionFailed  %+v", 412, o.Payload)
}
func (o *ServiceBindingUnbindingPreconditionFailed) GetPayload() *models.Error {
	return o.Payload
}

func (o *ServiceBindingUnbindingPreconditionFailed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceBindingUnbindingUnprocessableEntity creates a ServiceBindingUnbindingUnprocessableEntity with default headers values
func NewServiceBindingUnbindingUnprocessableEntity() *ServiceBindingUnbindingUnprocessableEntity {
	return &ServiceBindingUnbindingUnprocessableEntity{}
}

/* ServiceBindingUnbindingUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable Entity
*/
type ServiceBindingUnbindingUnprocessableEntity struct {
	Payload *models.Error
}

func (o *ServiceBindingUnbindingUnprocessableEntity) Error() string {
	return fmt.Sprintf("[DELETE /v2/service_instances/{instance_id}/service_bindings/{binding_id}][%d] serviceBindingUnbindingUnprocessableEntity  %+v", 422, o.Payload)
}
func (o *ServiceBindingUnbindingUnprocessableEntity) GetPayload() *models.Error {
	return o.Payload
}

func (o *ServiceBindingUnbindingUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewServiceBindingUnbindingDefault creates a ServiceBindingUnbindingDefault with default headers values
func NewServiceBindingUnbindingDefault(code int) *ServiceBindingUnbindingDefault {
	return &ServiceBindingUnbindingDefault{
		_statusCode: code,
	}
}

/* ServiceBindingUnbindingDefault describes a response with status code -1, with default header values.

Unexpected
*/
type ServiceBindingUnbindingDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the service binding unbinding default response
func (o *ServiceBindingUnbindingDefault) Code() int {
	return o._statusCode
}

func (o *ServiceBindingUnbindingDefault) Error() string {
	return fmt.Sprintf("[DELETE /v2/service_instances/{instance_id}/service_bindings/{binding_id}][%d] serviceBinding.unbinding default  %+v", o._statusCode, o.Payload)
}
func (o *ServiceBindingUnbindingDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *ServiceBindingUnbindingDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
